language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - pip install pip -U
  #- pip install -r requirements.txt
  - poetry install
# command to run tests
script: python test/test_core.py
